version: '3'
services:
  MariaDB:
    restart: always
    image: mariadb:10.2.11
    ports:
      - "${STAM_DB_PORT}:3306"
    environment:
      - DEBUG=true
      - MYSQL_USER=${STAM_DB_USERNAME}
      - MYSQL_PASSWORD=${STAM_DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${STAM_DB_PASSWORD}
      - MYSQL_DATABASE=${STAM_DB_DATABASE}
  Neo4J:
    restart: always
    image: neo4j:latest
    network_mode: "bridge"
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none
